### ISSUE TITLE
Feature: Improve board perspective for black

### ISSUE THREAD

**Issue by eemike07** [hrushikeshrv/chessengine#30] opened 2022-10-02 14:54 UTC
I would like to tackle this issue for Hacktoberfest.

When playing as black, the perspective of the board is upside down.
The black pieces should be at the bottom rather than playing from at the top.
The lettering should be:
1
2
3
4
5
6
7
8
  h  g  f  e  d  c  b  a

**Comment by hrushikeshrv** [comment] 2022-10-03 02:06
Sounds good 👍🏻 I'll assign this issue to you. 
The `Board.__repr__` method is responsible for returning the string representation of the board. Let me know if you need any help.

**Comment by eemike07** [comment] 2022-10-04 02:29
I got this working when playing against a computer, however, I've found something rather odd and confusing -

`self.opponent_side` is actually you, yourself being the player.
`self.side` is actually with respect to the computer.


From `play.py`
```python
        if player_side.lower().strip().startswith("w"):
            b = Board("black")
        else:
            b = Board("white")
        b.play()
```
It'll initialize the Board's side with `black` if you choose `white`....and setting `opponent_side` to `white`

within `bitboard.py` 
```python
        while True:
           ......
            if side_to_move == self.side:
               # Do Computer Moves Here....
            else:
                # ask for user input until accepted:
                input_accepted = False
                move_undone = False
```


Shouldn't `self.opponent_side` always be the computer?
This should probably be refactored//resolved as another issue.

**Comment by hrushikeshrv** [comment] 2022-10-04 06:24
Yeah, this is as intended. I've set `Board.side` to be the side that the _computer_ will be playing, and considered the human player to be the opponent, hence the human player is assigned `Board.opponent_side`. I'll add this assignment convention to the docs. I hope I could clarify :)

**Comment by eemike07** [comment] 2022-10-04 12:01
Ah, that makes sense.

**Closed as completed** 2022-10-05 04:59 UTC
Labels: hacktoberfest
